#!/bin/bash

# Get the default sink id
sink=$(pactl info | grep 'Default Sink' | cut -d' ' -f3)

# Extract the volume level and the mute state from the default sink
volume=$(pactl list sinks | grep -A 15 'Name: '$sink'' | grep 'Volume:' | grep -E -v 'Base Volume:' | awk -F : '{print $3}' | grep -o -P '.{0,3}%' | tr -d '%' | awk '{print $1}')
mute=$(pactl list sinks | grep -A 15 'Name: '$sink'' | grep -m 1 Mute | awk '{print $2}')

if [ "$mute" = "yes" ]; then
	echo "  $volume%"
else
	echo "   $volume%"
fi
